version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/app:/app/app

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpass
      POSTGRES_DB: ml_trader
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A backend.app.worker.celery_worker worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - api
      - redis
    volumes:
      - ./backend/app:/app/app

volumes:
  pgdata: