version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpass
      POSTGRES_DB: ml_trader
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: