"""Create initial tables

Revision ID: 0001
Revises: 
Create Date: 2023-05-10

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create all tables first
    op.create_table(
        'market_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('open', sa.Float(), nullable=False),
        sa.Column('high', sa.Float(), nullable=False),
        sa.Column('low', sa.Float(), nullable=False),
        sa.Column('close', sa.Float(), nullable=False),
        sa.Column('volume', sa.Float(), nullable=False),
        sa.Column('adjusted_close', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'timestamp'),
        sa.UniqueConstraint('symbol', 'timestamp', name='uix_market_data_symbol_timestamp')
    )
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    
    # Create economic_indicators table
    op.create_table(
        'economic_indicators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('indicator_code', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'timestamp'),
        sa.UniqueConstraint('indicator_code', 'timestamp', name='uix_economic_indicators_code_timestamp')
    )
    op.create_index(op.f('ix_economic_indicators_id'), 'economic_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_economic_indicators_indicator_code'), 'economic_indicators', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_economic_indicators_timestamp'), 'economic_indicators', ['timestamp'], unique=False)
    
    # Create technical_indicators table
    op.create_table(
        'technical_indicators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('indicator_name', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'timestamp'),
        sa.UniqueConstraint('symbol', 'indicator_name', 'timestamp', name='uix_technical_indicators')
    )
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_indicator_name'), 'technical_indicators', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_technical_indicators_symbol'), 'technical_indicators', ['symbol'], unique=False)
    op.create_index(op.f('ix_technical_indicators_timestamp'), 'technical_indicators', ['timestamp'], unique=False)
    
    # Create ml_models table
    op.create_table(
        'ml_models',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('model_type', sa.String(), nullable=False),
        sa.Column('features', sa.JSON(), nullable=False),
        sa.Column('target', sa.String(), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=False),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('model_path', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('trained_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_index(op.f('ix_ml_models_model_type'), 'ml_models', ['model_type'], unique=False)
    
    # Create backtest_results table
    op.create_table(
        'backtest_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('symbols', sa.JSON(), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=False),
        sa.Column('metrics', sa.JSON(), nullable=False),
        sa.Column('equity_curve', sa.JSON(), nullable=True),
        sa.Column('trades', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_results_model_id'), 'backtest_results', ['model_id'], unique=False)
    # ### end Alembic commands ###
    
    # Create TimescaleDB hypertables
    # This needs to be executed as SQL directly
    op.execute(
        """
        SELECT create_hypertable('market_data', 'timestamp', chunk_time_interval => interval '1 day');
        SELECT create_hypertable('economic_indicators', 'timestamp', chunk_time_interval => interval '1 day');
        SELECT create_hypertable('technical_indicators', 'timestamp', chunk_time_interval => interval '1 day');
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_results_model_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_ml_models_model_type'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_technical_indicators_timestamp'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_symbol'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_indicator_name'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_economic_indicators_timestamp'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_indicator_code'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_id'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ### 